name: Project Build Check

on:
  push:
    branches:
      - master

jobs:
  build-on-windows:
    name: Build on Windows
    # The windows-latest agent runs on 2022,
    # which does not have ATL libraries preinstalled yet?
    # There was a bug report for 2019 that got it fixed on GitHub,
    # but it seems the fix was not carried on to 2022
    runs-on: windows-2019
    steps:
      - name: Checkout repositories
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          lfs: false
          submodules: true
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x86
          vs-prerelease: true
      - name: Directory Check
        shell: pwsh
        run: |
          dir
          cd objson
          dir
          cd ../obse
          dir
          cd ../json
          dir
      - name: Build project
        shell: pwsh
        run: |
          msbuild objson/objson.vcxproj -p:BuildInParallel=true
