name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout repositories
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: Build project
        shell: pwsh
        run: |
          msbuild confse/confse.vcxproj -p:BuildInParallel=true
