name: CI

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PROJECT_PATH: confse/confse.vcxproj

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout repositories
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: Build project
        shell: pwsh
        run: |
          msbuild ${{ env.PROJECT_PATH }} -p:BuildInParallel=true
